name: test build in jh

on:
  push:
    branches:
      - jh
  workflow_dispatch:

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out 分支 jh
        uses: actions/checkout@v2
        with:
          ref: jh

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: 安装依赖
        run: |
          cd frontend
          npm install

      - name: 构建Nuxt app
        run: | 
          cd frontend
          npm run generate

      - name: 部署至github page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  # 确保路径是生成的静态文件夹
